personality = "pragmatic"

[projects."/Users/nelfimov/Documents/Dev/Infrastructure/rees46-infrastructure"]
trust_level = "trusted"

[projects."/Users/nelfimov/Documents/Dev/Rust/rees46-mcp"]
trust_level = "trusted"

[projects."/Users/nelfimov/Documents/Dev/JS/rees46-workers"]
trust_level = "trusted"

[projects."/Users/nelfimov/Documents/Dev/Ruby/rees46-dashboard-v2"]
trust_level = "trusted"

[projects."/Users/nelfimov/Documents/Dev/JS/rees46-js-sdk"]
trust_level = "trusted"

[projects."/Users/nelfimov/Documents/Dev/dotfiles"]
trust_level = "trusted"

[projects."/workspace"]
trust_level = "trusted"

[projects."/Users/nelfimov/Documents/Dev/Obsidian"]
trust_level = "trusted"

[projects."/Users/nelfimov/Documents/Dev/Ruby/rees46-dashboard"]
trust_level = "trusted"

[projects."/Users/nelfimov/Documents/Dev/Infrastructure/rees46-workflow"]
trust_level = "trusted"

[projects."/Users/nelfimov/Documents/Dev/JS/rees46-shopify-app"]
trust_level = "trusted"

[projects."/Users/nelfimov/Documents/Dev/Ruby/rees46-api-rails"]
trust_level = "trusted"

[projects."/Users/nelfimov/Documents/Dev/Python/rees46-ai-analyst"]
trust_level = "trusted"

[projects."/Users/nelfimov/Documents/Dev/JS/rees46-documentation-unified"]
trust_level = "trusted"

[projects."/Users/nelfimov/Documents/Dev/Python/rees46-ml-tasks"]
trust_level = "trusted"

[projects."/Users/nelfimov/Documents/Dev/Infrastructure/nelfimov-infrastructure"]
trust_level = "trusted"

[projects."/Users/nelfimov/Documents/Dev/JS/rees46-web"]
trust_level = "trusted"

[projects."/Users/nelfimov/Documents/Dev/JS/rees46-cms"]
trust_level = "trusted"

[projects."/Users/nelfimov/Documents/Dev/Rust/rees46-probability-to-purchase"]
trust_level = "trusted"

[tui]
notifications = ["agent-turn-complete", "approval-requested"]
notification_condition = "always"
vim_mode_default = false

[tui.model_availability_nux]
"gpt-5.5" = 4

[plugins."github@openai-curated"]
enabled = true
