[settings]
# Disable each space by default. When this is set, Use the
# toggle_space_activated command to enable a space.
default_disable = false

# Focus the window under the mouse as it moves.
focus_follows_mouse = false

# Move the mouse to the middle of the window each time the focus changes.
mouse_follows_focus = false

default_keys = true

[keys]
# Toggle whether the focused node takes up the whole screen.
"Alt + Shift + F" = "toggle_fullscreen"

[settings.experimental]
# Show the current space index on the status icon.
status_icon.space_index = true

# Use color in the icon.
status_icon.color = false
