views:
  v1/pods:
    sortColumn: NAMESPACE:asc
    columns:
      - AGE
      - NAMESPACE
      - NAME
      - STATUS
      - READY
      - MEM/RL|S
      - NODE
      - CPU
      - MEM
      - IP|H
      - PF|H
      - "%CPU/R|H"
      - "%CPU/L|H"
      - "%MEM/L|H"
      - "%MEM/R|H"
