k9s:
  cluster: rees46-stage
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - default
  view:
    active: v1/pods
  featureGates:
    nodeShell: false
  proxy: null
