theme = "dracula"

[editor]
line-number = "relative"
bufferline = "multiple"
default-yank-register = "+"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
rainbow-option = "normal"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true
display-messages = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "warning"

[keys.normal]
"space" = { "," = "buffer_picker", "space" = "file_picker", "f" = "file_picker_in_current_buffer_directory", "q" = { "q" = ":quit-all" }, "g" = { "g" = [
  ":write-all",
  ":new",
  ":insert-output lazygit >/dev/tty",
  ":set mouse false",
  ":set mouse true",
  ":buffer-close!",
  ":redraw",
  ":reload-all",
] } }

"K" = "hover"
S-l = ":buffer-next"
S-h = ":buffer-previous"
# s = "goto_word"
